#A Descent Essentials Kit Preview Config File!
#You can change all the tags and messages for the plugin here!

#Color codes: https://www.spigotmc.org/wiki/textcosmetics-colors-and-formats/

#Placeholders:
#plugin chat tag = {tag}
#kit name = {kitname}
#money from kit = {money}
#command from kit = {command}

#Plugin chat tag
tag: "&6[ADEKP]"

#Plugin messages
#All can use {tag}
#Can use {kitname}
startChatList: "{tag} Additional items in the &c{kitname}&6 kit!"
enchdChatList: "{tag} End of additional items in the &c{kitname}&6 kit!"
#Can use {money}
moneyAddMsg: "&6- &c{money}&6 will be added to your account!"
#Can use {command}
commandAddMsg: "&6- The command: &c{command}&6 will be run!"

#Permissions messages
#All can use {tag}
cannotUseCommand: "&4You do not have access to that command."
cannotUseSign: "&4You cannot interact with that!"
isNotAPlayer: "You must be a Player to send this command."

#NO NOT TOUCH
version: 1.0.0