name: ADEKP
version: 1.0.2
author: Allogeneous
main: me.Allogeneous.ADEKP.ADEKPMain
depend: [Essentials]

commands:
    ekitpreview:
        description: Command to preview kits
        usage: "/ekitpreview <kit name>"
        aliases: [ekp, epk, epreviewkit, eshowkit]
    adekpreload:
        description: Reloads the config file for the plugin
        usage: "/adekpreload"

permissions:
    adekp.kitpreview:
        description: Allows usage of /ekitpreview
        default: true
    adekp.kitpreviewmoney:
        description: Allows user to see the money they will get from the kit in chat
        default: true
    adekp.kitpreviewcommands:
        description: Allows user to see what commands will be run when they get the kit in chat
        default: true
    adekp.kitpreviewusesign:
        description: Allows user to preview a kit when clicking on a sign
        default: true
    adekp.kitpreviewcreatesign:
        description: Allows user to create and destroy a kit preview sign
        default: op
    adekp.kitpreviewreloadconfig:
        description: Allows user to reload the plugin configuration file
        default: op